/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EnvelopesRouteImport } from './routes/envelopes'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as ApiPublicTransactionsRouteImport } from './routes/api.public.transactions'
import { Route as ApiPublicPruneAuditRouteImport } from './routes/api.public.prune-audit'
import { Route as ApiPublicProcessRecurringRouteImport } from './routes/api.public.process-recurring'
import { Route as ApiPublicMetricsRouteImport } from './routes/api.public.metrics'
import { Route as ApiPublicCategoriesRouteImport } from './routes/api.public.categories'
import { Route as ApiPublicAttachmentsRouteImport } from './routes/api.public.attachments'
import { Route as ApiPublicAccountsRouteImport } from './routes/api.public.accounts'
import { Route as ApiNextcloudCallbackRouteImport } from './routes/api.nextcloud.callback'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopesRoute = EnvelopesRouteImport.update({
  id: '/envelopes',
  path: '/envelopes',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTransactionsRoute = ApiPublicTransactionsRouteImport.update({
  id: '/api/public/transactions',
  path: '/api/public/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPruneAuditRoute = ApiPublicPruneAuditRouteImport.update({
  id: '/api/public/prune-audit',
  path: '/api/public/prune-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessRecurringRoute =
  ApiPublicProcessRecurringRouteImport.update({
    id: '/api/public/process-recurring',
    path: '/api/public/process-recurring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriesRoute = ApiPublicCategoriesRouteImport.update({
  id: '/api/public/categories',
  path: '/api/public/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttachmentsRoute = ApiPublicAttachmentsRouteImport.update({
  id: '/api/public/attachments',
  path: '/api/public/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountsRoute = ApiPublicAccountsRouteImport.update({
  id: '/api/public/accounts',
  path: '/api/public/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNextcloudCallbackRoute = ApiNextcloudCallbackRouteImport.update({
  id: '/api/nextcloud/callback',
  path: '/api/nextcloud/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
  '/api/public/accounts': typeof ApiPublicAccountsRoute
  '/api/public/attachments': typeof ApiPublicAttachmentsRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/process-recurring': typeof ApiPublicProcessRecurringRoute
  '/api/public/prune-audit': typeof ApiPublicPruneAuditRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
  '/api/public/accounts': typeof ApiPublicAccountsRoute
  '/api/public/attachments': typeof ApiPublicAttachmentsRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/process-recurring': typeof ApiPublicProcessRecurringRoute
  '/api/public/prune-audit': typeof ApiPublicPruneAuditRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
  '/api/public/accounts': typeof ApiPublicAccountsRoute
  '/api/public/attachments': typeof ApiPublicAttachmentsRoute
  '/api/public/categories': typeof ApiPublicCategoriesRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/process-recurring': typeof ApiPublicProcessRecurringRoute
  '/api/public/prune-audit': typeof ApiPublicPruneAuditRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/envelopes'
    | '/insights'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
    | '/api/public/accounts'
    | '/api/public/attachments'
    | '/api/public/categories'
    | '/api/public/metrics'
    | '/api/public/process-recurring'
    | '/api/public/prune-audit'
    | '/api/public/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/envelopes'
    | '/insights'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
    | '/api/public/accounts'
    | '/api/public/attachments'
    | '/api/public/categories'
    | '/api/public/metrics'
    | '/api/public/process-recurring'
    | '/api/public/prune-audit'
    | '/api/public/transactions'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/envelopes'
    | '/insights'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
    | '/api/public/accounts'
    | '/api/public/attachments'
    | '/api/public/categories'
    | '/api/public/metrics'
    | '/api/public/process-recurring'
    | '/api/public/prune-audit'
    | '/api/public/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  EnvelopesRoute: typeof EnvelopesRoute
  InsightsRoute: typeof InsightsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  EditIdRoute: typeof EditIdRoute
  ApiNextcloudCallbackRoute: typeof ApiNextcloudCallbackRoute
  ApiPublicAccountsRoute: typeof ApiPublicAccountsRoute
  ApiPublicAttachmentsRoute: typeof ApiPublicAttachmentsRoute
  ApiPublicCategoriesRoute: typeof ApiPublicCategoriesRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
  ApiPublicProcessRecurringRoute: typeof ApiPublicProcessRecurringRoute
  ApiPublicPruneAuditRoute: typeof ApiPublicPruneAuditRoute
  ApiPublicTransactionsRoute: typeof ApiPublicTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelopes': {
      id: '/envelopes'
      path: '/envelopes'
      fullPath: '/envelopes'
      preLoaderRoute: typeof EnvelopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transactions': {
      id: '/api/public/transactions'
      path: '/api/public/transactions'
      fullPath: '/api/public/transactions'
      preLoaderRoute: typeof ApiPublicTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prune-audit': {
      id: '/api/public/prune-audit'
      path: '/api/public/prune-audit'
      fullPath: '/api/public/prune-audit'
      preLoaderRoute: typeof ApiPublicPruneAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-recurring': {
      id: '/api/public/process-recurring'
      path: '/api/public/process-recurring'
      fullPath: '/api/public/process-recurring'
      preLoaderRoute: typeof ApiPublicProcessRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categories': {
      id: '/api/public/categories'
      path: '/api/public/categories'
      fullPath: '/api/public/categories'
      preLoaderRoute: typeof ApiPublicCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attachments': {
      id: '/api/public/attachments'
      path: '/api/public/attachments'
      fullPath: '/api/public/attachments'
      preLoaderRoute: typeof ApiPublicAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accounts': {
      id: '/api/public/accounts'
      path: '/api/public/accounts'
      fullPath: '/api/public/accounts'
      preLoaderRoute: typeof ApiPublicAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nextcloud/callback': {
      id: '/api/nextcloud/callback'
      path: '/api/nextcloud/callback'
      fullPath: '/api/nextcloud/callback'
      preLoaderRoute: typeof ApiNextcloudCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  EnvelopesRoute: EnvelopesRoute,
  InsightsRoute: InsightsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  EditIdRoute: EditIdRoute,
  ApiNextcloudCallbackRoute: ApiNextcloudCallbackRoute,
  ApiPublicAccountsRoute: ApiPublicAccountsRoute,
  ApiPublicAttachmentsRoute: ApiPublicAttachmentsRoute,
  ApiPublicCategoriesRoute: ApiPublicCategoriesRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
  ApiPublicProcessRecurringRoute: ApiPublicProcessRecurringRoute,
  ApiPublicPruneAuditRoute: ApiPublicPruneAuditRoute,
  ApiPublicTransactionsRoute: ApiPublicTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
