/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EnvelopesRouteImport } from './routes/envelopes'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as ApiNextcloudCallbackRouteImport } from './routes/api.nextcloud.callback'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopesRoute = EnvelopesRouteImport.update({
  id: '/envelopes',
  path: '/envelopes',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNextcloudCallbackRoute = ApiNextcloudCallbackRouteImport.update({
  id: '/api/nextcloud/callback',
  path: '/api/nextcloud/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/envelopes': typeof EnvelopesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/edit/$id': typeof EditIdRoute
  '/api/nextcloud/callback': typeof ApiNextcloudCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/envelopes'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/envelopes'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/envelopes'
    | '/settings'
    | '/transactions'
    | '/edit/$id'
    | '/api/nextcloud/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  EnvelopesRoute: typeof EnvelopesRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  EditIdRoute: typeof EditIdRoute
  ApiNextcloudCallbackRoute: typeof ApiNextcloudCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelopes': {
      id: '/envelopes'
      path: '/envelopes'
      fullPath: '/envelopes'
      preLoaderRoute: typeof EnvelopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nextcloud/callback': {
      id: '/api/nextcloud/callback'
      path: '/api/nextcloud/callback'
      fullPath: '/api/nextcloud/callback'
      preLoaderRoute: typeof ApiNextcloudCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  EnvelopesRoute: EnvelopesRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  EditIdRoute: EditIdRoute,
  ApiNextcloudCallbackRoute: ApiNextcloudCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
